 <x-app-layout>
     <header>
         @livewire('header')
     </header>
     <section>
        @livewire('slogan')
     </section>
     <section>
        @livewire('mapa')
     </section>
 </x-app-layout>
